project:
  type: website
  render:
    - index.qmd
    - proyectos.qmd
    - Publicaciones.qmd

title: "Portfolio de Valeria Aguirre"

website:
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Proyectos"
        href: proyectos.qmd
      - text: "Publicaciones"
        href: Publicaciones.qmd

    right:
      - icon: github
        href: https://github.com/Valeria-Aguirre
      - icon: linkedin
        href: https://www.linkedin.com/in/valeria-mariana-aguirre/
      - icon: envelope
        href: mailto:valumaru@hotmail.com

format:
  html:
    theme: readable
    css: css-styles.css
    font-sans: "Helvetica, Arial, sans-serif"
    font-mono: "Fira Code"